export enum EUniversalActionTypes {
  SHOW_LOADING = "[UNIVERSAL] SHOW_LOADING",
  CLOSE_LOADING = "[UNIVERSAL] CLOSE_LOADING",
  SWITCH_LANGUAGE = "[UNIVERSAL] SWITCH_LANGUAGE",
  UPDATE_MONTH_NAME = "[COMMON] UPDATE_MONTH_NAME",
  SET_KEYBOARD_HEIGHT = "[UNIVERSAL] SET_KEYBOARD_HEIGHT",
  UPDATE_CUSTOM_DATES = "[UNIVERSAL] UPDATE_CUSTOM_DATES",
}

export default EUniversalActionTypes;
