default_platform(:ios)

platform :ios do

  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Signing"
  lane :signing do
    create_keychain(
      name: "keychain",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true,
      password: "1234"
    )

    install_provisioning_profile(
      path: "./dhp.mobileprovision"
    )

    import_certificate(
      keychain_name: "keychain",
      certificate_path: "./certificates.p12",
      keychain_password: "1234",
      certificate_password: "1234"
    )
  end

  desc "build app"
  lane :buildApp do
    build_app(
        scheme: "PatientApp",
        workspace: "./ios/PatientApp.xcworkspace",
        export_method: 'enterprise',
        clean: true,
        xcargs: "CODE_SIGN_STYLE=Manual",
        skip_codesigning: true
    )
    
    #api_key = app_store_connect_api_key(
    #  key_id: "K8BZ3R738B",
    #  issuer_id: "a608bf17-7a5c-4bcc-a9e1-a0af6b321928",
    #  key_filepath: "./AuthKey_K8BZ3R738B.p8",
    #  duration: 1200, # optional (maximum 1200)
    #  in_house: false # optional but may be required if using match/sigh
    #)
    #upload_to_testflight(
    #  api_key: api_key,
    #  skip_submission: true,
    #  ipa: "PatientApp.ipa",
    #  skip_waiting_for_build_processing: true,
    #)
  end

  desc "do all lane above"
  lane :do_all_lane  do
    signing
    buildApp
  end
end
