export enum EAuthActionTypes {
  LOGIN_SUCCESS = "[AUTH] LOGIN_SUCCESS",
  LOG_OUT = "[AUTH] LOG_OUT",
  SET_LOG_OUT = "[AUTH] SET_LOG_OUT",
  CHANGE_PASSWORD = "[AUTH] CHANGE_PASSWORD",
  SET_LOGIN_MARK_TIME = "[AUTH] SET_LOGIN_MARK_TIME",
  SET_PATIENT_PROFILE = "[AUTH] SET_PATIENT_PROFILE",
}

export default EAuthActionTypes;
